### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by aditya-8-88** [GAGGZ1/Face-liveness-detection#2]
Building wheels for collected packages: Pillow, dlib
  Building wheel for Pillow (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for Pillow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [202 lines of output]

**Comment by GAGGZ1** [comment]
Yes I’m also trying to run it, but it’s not functioning as expected. I believe it might take some more time :-)

**Comment by GAGGZ1** [comment]
i was following these 2 videos 
1. https://www.youtube.com/watch?v=z_dbnYHAQYg
2. https://www.youtube.com/watch?v=_KvtVk8Gk1A&t=397s

**Comment by GAGGZ1** [comment]
try this
pip install Pillow
pip install dlib

**Comment by aditya-8-88** [comment]
```CMake is not installed on your system!```
I installed ```cmake``` on system level whereas used a virtual environment to install pillow, dlib and face_recognition

**Comment by aditya-8-88** [comment]
```bash
$ python main.py  
Please install `face_recognition_models` with this command before using `face_recognition`:
pip install git+https://github.com/ageitgey/face_recognition_models


$ pip install git+https://github.com/ageitgey/face_recognition_models
Collecting git+https://github.com/ageitgey/face_recognition_models
  Cloning https://github.com/ageitgey/face_recognition_models to /tmp/pip-req-build-b0p47_4v
  Running command git clone --filter=blob:none --quiet https://github.com/ageitgey/face_recognition_models /tmp/pip-req-build-b0p47_4v
  Resolved https://github.com/ageitgey/face_recognition_models to commit e67de717267507d1e9246de95692eb8be736ab61
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done


$ python main.py  
Please install `face_recognition_models` with this command before using `face_recognition`:

pip install git+https://github.com/ageitgey/face_recognition_models
```

how to resolve this.

**Comment by GAGGZ1** [comment]
in my macbook after watching this videos this issue was solved https://www.youtube.com/watch?v=pyILrM8pG40

**Comment by aditya-8-88** [comment]
yeah it worked.

i think the correct requirements.txt file could be:
```txt 
click==8.1.7
cmake==3.31.1
dlib==19.24.6
face-recognition==1.3.0
face_recognition_models==0.3.0
numpy==2.1.3
opencv-python==4.10.0.84
pillow==11.0.0
pip==24.2
setuptools==75.6.0
```

**Comment by GAGGZ1** [comment]
ohh nice
